name: Sync Labels

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '20'

      - name: 1. Get Labels from LacusSolutions/labels
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          echo "Getting labels from LacusSolutions/labels..."

          gh label list \
            --repo LacusSolutions/labels \
            --limit 100 \
            --json name,color,description > labels_modelo.json

          echo "Found labels:"
          cat labels_modelo.json

      - name: 2. Sync with this repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx github-label-sync \
            --access-token $GITHUB_TOKEN \
            --labels labels_modelo.json \
            --allow-added-labels \
            ${{ github.repository }}
